---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: espn-soccer
  namespace: n8n
  labels:
    app: espn-soccer
spec:
  output:
    to:
      kind: ImageStreamTag
      name: espn-soccer:latest
  source:
    type: Git
    git:
      uri: https://github.com/mfdii/mcp-espn-soccer.git
      ref: mcp-v2-migration
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  triggers:
  - type: ConfigChange
